### ISSUE TITLE
elasticnet???

### ISSUE THREAD

**Issue by xzbwx** [ToshihiroIguchi/elasticnet#1]
Hello,Toshihiro lguchi!
I was using the package "elasticnet" to deal with my data.
When I used the "predict()" function, I met an error "‘predict’ does not apply to the method of the target object c('double','numeric')" .
So I used "ret <- predict(result$glmnet, x, s = result$lambda)" instead of "ret <- predict(model$glmnet[[model$best_num]], x,s = model$lambda, type = 'class')"
I want to know if "model$best_num" will affect the result.
Thanks.

**Comment by ToshihiroIguchi** [comment]
Hello, xzbwx!
Thank you for your comment.

As you have taught me, I confirmed that there is a bug in the predict function.
I rewrote the predict function and confirmed that it works with my data.
(Part "[[model$best_num]]"  was unnecessary.)

I am glad that you can confirm that your data will work.

Thank you.
